[package]
name = "harris-corner-detector"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = "0.31.1"
env_logger = "0.11.8"
image = "0.25.6"
imageproc = "0.25.0"
log = "0.4.27"
realsense-rust = "1.2.3"
